"""empty message

Revision ID: bf24d220c3cb
Revises: dfb7be7c6295
Create Date: 2022-05-27 17:32:11.014859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf24d220c3cb'
down_revision = 'dfb7be7c6295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.add_column('venues', sa.Column('created_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'created_date')
    op.drop_column('artists', 'created_date')
    # ### end Alembic commands ###
